-- begin OFFICE_REQUEST
alter table OFFICE_REQUEST add constraint FK_OFFICE_REQUEST_APPLICANT foreign key (APPLICANT_ID) references SEC_USER(ID)^
alter table OFFICE_REQUEST add constraint FK_OFFICE_REQUEST_WORKER foreign key (WORKER_ID) references SEC_USER(ID)^
create unique index IDX_OFFICE_REQUEST_UNIQ_APPLICANT_ID on OFFICE_REQUEST (APPLICANT_ID) ^
-- end OFFICE_REQUEST

-- begin OFFICE_REQUEST_STATUS
alter table OFFICE_REQUEST_STATUS add constraint FK_OFFICE_REQUEST_STATUS_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID)^
alter table OFFICE_REQUEST_STATUS add constraint FK_OFFICE_REQUEST_STATUS_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_OFFICE_REQUEST_STATUS_REQUEST on OFFICE_REQUEST_STATUS (REQUEST_ID)^
create index IDX_OFFICE_REQUEST_STATUS_USER on OFFICE_REQUEST_STATUS (USER_ID)^
-- end OFFICE_REQUEST_STATUS
-- begin OFFICE_REQUEST_FILE
alter table OFFICE_REQUEST_FILE add constraint FK_OFFICE_REQUEST_FILE_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID)^
alter table OFFICE_REQUEST_FILE add constraint FK_OFFICE_REQUEST_FILE_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_OFFICE_REQUEST_FILE_REQUEST on OFFICE_REQUEST_FILE (REQUEST_ID)^
-- end OFFICE_REQUEST_FILE
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID)^
-- end SEC_USER

-- begin OFFICE_STEP
alter table OFFICE_STEP add constraint FK_OFFICE_STEP_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end OFFICE_STEP
-- begin OFFICE_STEP_ACTION
alter table OFFICE_STEP_ACTION add constraint FK_OFFICE_STEP_ACTION_STEP foreign key (STEP_ID) references OFFICE_STEP(ID)^
create index IDX_OFFICE_STEP_ACTION_STEP on OFFICE_STEP_ACTION (STEP_ID)^
-- end OFFICE_STEP_ACTION
-- begin OFFICE_REQUEST_ACTION
alter table OFFICE_REQUEST_ACTION add constraint FK_OFFICE_REQUEST_ACTION_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID)^
alter table OFFICE_REQUEST_ACTION add constraint FK_OFFICE_REQUEST_ACTION_ACT foreign key (ACT_ID) references OFFICE_STEP_ACTION(ID)^
create index IDX_OFFICE_REQUEST_ACTION_REQUEST on OFFICE_REQUEST_ACTION (REQUEST_ID)^
create index IDX_OFFICE_REQUEST_ACTION_ACT on OFFICE_REQUEST_ACTION (ACT_ID)^
-- end OFFICE_REQUEST_ACTION
