alter table OFFICE_REQUEST_ACTION add constraint FK_OFFICE_REQUEST_ACTION_REQUEST foreign key (REQUEST_ID) references OFFICE_REQUEST(ID);
alter table OFFICE_REQUEST_ACTION add constraint FK_OFFICE_REQUEST_ACTION_ACT foreign key (ACT_ID) references OFFICE_STEP_ACTION(ID);
create index IDX_OFFICE_REQUEST_ACTION_REQUEST on OFFICE_REQUEST_ACTION (REQUEST_ID);
create index IDX_OFFICE_REQUEST_ACTION_ACT on OFFICE_REQUEST_ACTION (ACT_ID);
